use Lab5;

SELECT PULPIT.PULPIT_NAME, FACULTY_NAME
FROM FACULTY, PULPIT
WHERE PULPIT.FACULTY = FACULTY.FACULTY
and PULPIT.FACULTY In (SELECT PROFESSION.FACULTY FROM PROFESSION
							  WHERE PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%' )

SELECT PULPIT.PULPIT_NAME, FACULTY_NAME
from PULPIT inner join FACULTY 
	on PULPIT.FACULTY = FACULTY.FACULTY 
	and 
	PULPIT.FACULTY In (SELECT PROFESSION.FACULTY FROM PROFESSION
							  WHERE PROFESSION_NAME like '%технология%' or PROFESSION_NAME like '%технологии%' )

SELECT distinct PULPIT.PULPIT_NAME, FACULTY_NAME
	FROM PULPIT
	inner join PROFESSION 
		on  (PROFESSION.PROFESSION_NAME like '%технология%' or PROFESSION.PROFESSION_NAME like '%технологии%')
	inner join FACULTY
		on PROFESSION.FACULTY = FACULTY.FACULTY and PROFESSION.FACULTY = PULPIT.FACULTY 

SELECT AUDITORIUM, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY FROM AUDITORIUM a
	WHERE AUDITORIUM_CAPACITY = (SELECT TOP(1) AUDITORIUM_CAPACITY FROM AUDITORIUM aa
										WHERE aa.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
										ORDER BY AUDITORIUM_CAPACITY DESC);

SELECT FACULTY.FACULTY_NAME
FROM FACULTY
	WHERE NOT EXISTS (SELECT * FROM PULPIT
						WHERE PULPIT.FACULTY = FACULTY.FACULTY);

SELECT TOP 1
	(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.[SUBJECT] LIKE 'ОАиП') [ОАиП],
	(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.[SUBJECT] LIKE 'СУБД') [СУБД],
	(SELECT AVG(NOTE) FROM PROGRESS WHERE PROGRESS.[SUBJECT] LIKE 'БД') [БД]
FROM PROGRESS

SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY >= ALL(SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
										WHERE AUDITORIUM_TYPE LIKE '%ЛК%');

SELECT * FROM AUDITORIUM
	WHERE AUDITORIUM_CAPACITY >= ANY(SELECT AUDITORIUM_CAPACITY FROM AUDITORIUM
											WHERE AUDITORIUM_TYPE LIKE '%ЛК%');