use Lab5;

Select 
	min(AUDITORIUM_CAPACITY) as 'min',
	max(AUDITORIUM_CAPACITY) as 'max',
	avg(AUDITORIUM_CAPACITY) as 'avg',
	sum(AUDITORIUM_CAPACITY) as 'sum_capacity',
	count(*) as 'count_of_auditoriums'
		from AUDITORIUM

--2.
Select
	AUDITORIUM_TYPE.AUDITORIUM_TYPENAME,
	min(AUDITORIUM_CAPACITY) as 'min',
	max(AUDITORIUM_CAPACITY) as 'max',
	avg(AUDITORIUM_CAPACITY) as 'avg',
	sum(AUDITORIUM_CAPACITY) as 'sum_capacity',
	count(*) as 'count_of_auditoriums'
		from AUDITORIUM inner join AUDITORIUM_TYPE
		on AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
		group by AUDITORIUM_TYPE.AUDITORIUM_TYPENAME

--3.
Select * From (
	select Case 
				when PROGRESS.NOTE = 10 then '10'
				when PROGRESS.NOTE between 8 and 9 then '8-9'
				when PROGRESS.NOTE between 6 and 7 then '6-7'
				else '4-5' 
				end [оценки], COUNT(*)[количество]
	from PROGRESS group by Case 
								when PROGRESS.NOTE = 10 then '10'
								when PROGRESS.NOTE between 8 and 9 then '8-9'
								when PROGRESS.NOTE between 6 and 7 then '6-7'
								else '4-5' 
								end
				) as T
Order by Case[оценки]
			when '10' then 1
			when '8-9' then 2
			when '6-7' then 3
			when '4-5' then 4
			else 0
			end

--4
select FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE;

-- перепис.запрос, в 4 задании так, чтобы исп оценки по БД и ОАиП
select FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from FACULTY inner join GROUPS
on FACULTY.FACULTY = GROUPS.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where PROGRESS.[SUBJECT]='СУБД' or PROGRESS.[SUBJECT] = 'ОАиП'
group by FACULTY.FACULTY, GROUPS.PROFESSION, GROUPS.COURSE;

--5 запрос, кот.выводит специальности, дисциплины и оценки на ТОВ с исп-нием ROLLUP
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY='ТОВ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY

Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY='ТОВ'
group by rollup (GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY)

--6
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY='ТОВ'
group by cube (GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY)

--7 запрос с рез-том сдачи экз-ов
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY
union all
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY

Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY
union
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY

--8
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY
intersect
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY;

--9
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ТОВ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY
except
Select GROUPS.PROFESSION, PROGRESS.[SUBJECT],GROUPS.FACULTY,
round (avg (cast (PROGRESS.NOTE as float(4))),2) as 'средняя оценка'
from GROUPS inner join FACULTY
on GROUPS.FACULTY = FACULTY.FACULTY
inner join STUDENT
on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PROGRESS
on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT
where GROUPS.FACULTY like 'ХТиТ'
group by GROUPS.PROFESSION, PROGRESS.[SUBJECT], GROUPS.FACULTY;

--10
select p1.SUBJECT, p1.NOTE,
(
	select COUNT(*) from PROGRESS p2
	where p2.SUBJECT = p1.SUBJECT and p2.NOTE = p1.NOTE
)[количество]
from PROGRESS p1
group by p1.SUBJECT, p1.NOTE
having NOTE between 8 and 9
order by NOTE;